# Generated by Django 3.2.12 on 2024-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composts',
            fields=[
                ('compost_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5000)),
                ('description', models.TextField()),
                ('available_units', models.IntegerField()),
                ('cost_per_unit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('compost_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('date_of_purchase', models.DateField()),
            ],
        ),
    ]
